name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Run containers
        run: docker compose up -d

      - name: Stop containers
        run: docker compose down
